[features]
seeds = false
skip-lint = false

[programs.devnet]
mint_nft = "HGe3pxwjU3o5ZTNvQG4GDiyNb3cDeSLuw1EFS6MzeCak"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/xueshan/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
log-data = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/log-data.ts"
set-sale-pda = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-set-sale-pda.ts"
